services:
  postgres:
    image: postgres:16-alpine
    container_name: pg
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME:?error}
      POSTGRES_USER: ${POSTGRES_DB_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD:?error}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
          condition: service_healthy
    restart: unless-stopped
    volumes:
      - ../src:/app
      - ../certs:/app/certs
      - ../secrets:/app/secrets:ro
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped
  garage:
    image: dxflrs/garage:v2.3.0
    container_name: garage
    restart: unless-stopped
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
    volumes:
      - ../garage.toml:/etc/garage.toml:ro
      - ./data/meta:/var/lib/garage/meta
      - ./data/data:/var/lib/garage/data
volumes:
  pgdata:
  garage-data:
  garage-meta:
