"""move sent_at, send_at attributes from user_capsule to capsule table

Revision ID: e0b280da1a5d
Revises: 665216580337
Create Date: 2026-07-01 06:33:27.489426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e0b280da1a5d"
down_revision: Union[str, Sequence[str], None] = "665216580337"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("capsules", sa.Column("send_at", sa.DateTime(), nullable=True))
    op.add_column("capsules", sa.Column("sent_at", sa.DateTime(), nullable=True))
    op.drop_column("user_capsule", "is_sent")
    op.drop_column("user_capsule", "send_at")
    op.drop_column("user_capsule", "sent_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_capsule",
        sa.Column(
            "sent_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "user_capsule",
        sa.Column(
            "send_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "user_capsule",
        sa.Column("is_sent", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("capsules", "sent_at")
    op.drop_column("capsules", "send_at")
    # ### end Alembic commands ###
