"""add capsules and user_capsule tables

Revision ID: 5b40592ff2e5
Revises: 91a23a31c261
Create Date: 2026-06-10 07:50:37.915567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b40592ff2e5"
down_revision: Union[str, Sequence[str], None] = "91a23a31c261"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capsules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=20), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_capsule",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("capsule_id", sa.Integer(), nullable=False),
        sa.Column("send_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("is_sent", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["capsule_id"], ["capsules.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "capsule_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_capsule")
    op.drop_table("capsules")
    # ### end Alembic commands ###
