"""add verificator_id column to users table

Revision ID: 42c0af4d8084
Revises: 88e24f79f647
Create Date: 2026-06-20 07:16:10.008224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42c0af4d8084"
down_revision: Union[str, Sequence[str], None] = "88e24f79f647"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("verificator_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "users", "users", ["verificator_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "verificator_id")
    # ### end Alembic commands ###
